### PR TITLE
Cast self.viewController.webView in AppDelegate+notification.m

### PR DESCRIPTION
**Pull request by ahmozkya**
Cast please.

### CODE REVIEW

**Comment by matzew** [comment]
@ahmozkya hi, what's the bug here? mind filing a JIRA at https://issues.jboss.org/browse/AGCORDOVA ?  

Thanks!

**Comment by ahmozkya** [comment]
Hi @matzew 

Please check following issue:
https://issues.jboss.org/projects/AGCORDOVA/issues/AGCORDOVA-144?filter=allopenissues

Env:
  - OSX 10.11.5
  - XCode 7.3.1

Desc:
Without casting with webView, compiler cannot find **isLoading** method.

**Comment by matzew** [comment]
@corinnekrych @edewit any comments

**Comment by edewit** [comment]
@ahmozkya sorry for my late reply, I can confirm that your fix removes one error, but I still have another:

```bash
/test/platforms/ios/HelloCordova/Plugins/aerogear-cordova-push/AGPushPlugin.m:147:61: error: use of undeclared identifier 'arguments'
    DLog(@"setApplicationIconBadgeNumber:%@\n withDict:%@", arguments, options);
                                                            ^
//test/platforms/ios/HelloCordova/Plugins/aerogear-cordova-push/AGPushPlugin.m:147:72: error: use of undeclared identifier 'options'
    DLog(@"setApplicationIconBadgeNumber:%@\n withDict:%@", arguments, options);
```
Why don't we replace this with:

```
    NSLog(@"setApplicationIconBadgeNumber:%@", command.arguments);
```

**Pull request merged**
