### PR TITLE
update ios lib

### PR DESCRIPTION
**Pull request by wei-lee**
@edewit @corinnekrych  looks like we need to update the ios lib as well. It's missing the armv7s architecture when build cordova apps on BF.

### CODE REVIEW

**Comment by matzew** [comment]
:tada: awesome, @wei-lee 

Not 100% on the actual file name if it should be `libpush-sdk-1.1.1.a`, after coming from 1.1.0-beta.

But that's minor, especially that the UPS 1.1.1 is coming somewhat soon, I guess the 1.1.1 is reasonable :grinning:

**Comment by wei-lee** [comment]
@matzew Oh, I built this version from the master branch of the aerogear-ios repo. Is that version not released yet? Perhaps I should not use this version then?

**Comment by matzew** [comment]
Ah, nevermind, @wei-lee 

https://github.com/aerogear/aerogear-ios-push/releases/tag/1.1.1

:-)

Sorry for that confusion :-)

**Comment by wei-lee** [comment]
@matzew no problem at all.

**Comment by edewit** [comment]
@wei-lee sorry but I merged the release branch back to compat because that one was tested

**Comment by wei-lee** [comment]
@edewit no problem at all. Didn't know we already have a fix in another branch. Thanks.

**Pull request closed without merging**
