### PR TITLE
AGCORDOVA-132 userData should be called user-data and of type string

### PR DESCRIPTION
**Pull request by edewit**
How to test
=========
remove the currently installed push plugin:
```bash
$ cordova plugin rm aerogear-cordova-push
```
install my branch:
```bash
$ cordova plugin add https://github.com/edewit/aerogear-pushplugin-cordova#user-data
```

### CODE REVIEW

**Comment by LazorJack** [comment]
Okay, so I figured out what the issue is.

NotificationMessageHandler.onMessage(Context context, Bundle message)
- When this method is called, all user data is exploded into the top level of message already.

So lets say I called a push notification with user-data: {"one" : "One", "two" : "Two" }

the issue comes about in this method:

`    public Bundle toBundle() {
        Bundle bundle = new Bundle(5);
        bundle.putString("alert", alert);
        bundle.putString("sound", sound);
        bundle.putString("badge", String.valueOf(badge));
        bundle.putString("aerogear-push-id", aerogearPushId);
        bundle.putString("user-data", userData);
        return bundle;
    }`

since it was already expanded in the notificationMessageHandler, you would want to say something like (just for this scenario)
        bundle.putString("one", userData.getOne());
        bundle.putString("two", userData.getTwo());



Looks like a workaround could be wrapping your user data in a json object called "user-data" so that way the code picks it up.

**Comment by edewit** [comment]
Hi @LazorJack,

Right the user-data is a json string in the bundle, but the Plugin will [convert it to a json object](https://github.com/aerogear/aerogear-cordova-push/blob/ca35949b1962153394ae1dda4bd933b6c1b89671/src/android/org/jboss/aerogear/cordova/push/PushPlugin.java#L296) and send that to the javascript callback. So when you say: "I ran into the same problem" what do you mean?

**Comment by edewit** [comment]
Tested it one more time and wrote it down so you can just copy paste:
```bash
cordova create userdata
cd userdata
cordova plugin add https://github.com/edewit/aerogear-pushplugin-cordova\#user-data
cordova platform add android
cp plugins/aerogear-cordova-push/example/* www 
vim www/index.html
# update variantID variantSecret and senderID
```
Then I update [line 54](https://github.com/aerogear/aerogear-cordova-push/blob/master/example/index.html#L54) to this:
```javascript
statusList.append('<li>MESSAGE -> MSG: ' + e.alert + e.payload.test + '</li>');
```
and send a curl:
```bash
curl -u "00000-0000-0000-0000-000:00-0000"  \                                
   -v -H "Accept: application/json" -H "Content-type: application/json"  \
   -X POST  -d \
  '{
     "message": {
      "alert": "Hello ",
      "sound": "default",
      "user-data": {
          "test": "I am the user data"
      }
     }
   }'  \
   https://ups-youraccount.rhcloud.com/ag-push/rest/sender
```
In the app I get a notification that reads `Hello I am the user data`

Does that work for you as well?

**Comment by LazorJack** [comment]
I apologize if I was vague, the issue I am facing is the user-data not being in the notification payload if the device is not in the foreground.

I added a second debug statement to NotificationMessageHandler.onMessage(Context context, Bundle message)

` Log.d(TAG, "onMessage - message: " + message);
`
Looking at the structure of the message it looks like you expect the structure of message to be:

```
{
  "alert" : "This is the alert",
  "sound" : "1",
  "badge": "-1",
  "aerogear-push-id" : "1111aaaacccc2222",
  "user-data" : {
    "one" : "One",
    "two" : "Two"
  }
}
```

But the debug log showed me that when it reaches the onMessage method, the structure of the message is actually

```
{
  "alert" : "This is the alert",
  "sound" : "1",
  "badge": "-1",
  "aerogear-push-id" : "1111aaaacccc2222",
  "one" : "One",
  "two" : "Two"
}
```

and then since you are looking for "user-data" it is not there.

I will try your suggestion now but I wanted to make sure I explained myself better.

Thanks!

**Comment by LazorJack** [comment]
Okay, so I tested out your example and I got what I expected.  When the app was in the foreground everything worked as expected but when it was not in the foreground, the user-data was not present.  This is a screen shot of what I experienced.  The "Hello undefined" is from when the app was in the background.

screenshot_2016-03-11-10-50-51

**Comment by edewit** [comment]
@LazorJack don't know what I have been testing, but now I've really fixed it, sorry

**Comment by LazorJack** [comment]
@edewit No worries at all, glad I could help.

**Pull request merged**
