### PR TITLE
updating version

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by edewit** [comment]
this is normally part of the [release process](https://github.com/aerogear/collateral/wiki/Release-Process-(Cordova)) but we can do it now as well

**Comment by matzew** [comment]
Right, after n gets released the version is updated to n+1.

So after 1.0.3 is out, the branch will be 1.0.4(-SNAPSHOT)

**Comment by edewit** [comment]
okay I'll update it again when we release

**Comment by matzew** [comment]
+1

On Thu, May 7, 2015 at 1:47 PM, Erik Jan de Wit <notifications@github.com>
wrote:

> okay I'll update it again when we release
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-cordova-push/pull/66#issuecomment-99830039>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
