### PR TITLE
fix: add channel for Android O

### PR DESCRIPTION
**Pull request by wtrocki**
Adding required channel for notifications.

# Verification

`cordova plugin add https://github.com/wtrocki/aerogear-cordova-push#fix-channels`

Notes: This change requires android O.

### CODE REVIEW

**Comment by wtrocki** [comment]
@danielpassos This normally need to be fixed in the android library. Patched that until we will get something more solid in place.

**Comment by danielpassos** [comment]
@wtrocki I don't think so, Android lib not provides a notification handler

**Comment by wtrocki** [comment]
Change is not fixing the core of the problem. I introduced new library that breaks cordova build chain.

**Comment by danielpassos** [comment]
Closed in favor of https://github.com/aerogear/aerogear-cordova-push/pull/125

**Pull request closed without merging**
