### PR TITLE
Using custom notification icon in android

### PR DESCRIPTION
**Pull request by drmistral**
This change allows, on notification,  to show the custom (small white) notification icon instead of the default one. 

1. Icon has to be named notification.png

2. Icon must reside in res/android/ and must be declared in config.xml
```
<platform name="android"> 
   ... 
   <icon src="res/android/notification.png" /> 
   ...
</platform>
```

3. The icon file should be copied (automatically at build time or by hand) in 

`platforms/android/res/drawable`

### CODE REVIEW

**Comment by danielpassos** [comment]
Can you rebase it?

**Comment by drmistral** [comment]
@danielpassos rebase done

**Comment by danielpassos** [comment]
@drmistral Thanks, give people some time to test the version I just release fixing the notification_id problem and I will play/test/review this.

**Comment by danielpassos** [comment]
Closed in favor of https://github.com/aerogear/aerogear-cordova-push/pull/128

**Pull request closed without merging**
