### PR TITLE
lib with enable bitcode

### PR DESCRIPTION
**Pull request by corinnekrych**
@faisakhtar for you to test
cc @edewit

### CODE REVIEW

**Comment by edewit** [comment]
@faisakhtar to test:
```bash
cordova plugin rm aerogear-cordova-push
cordova plugin add https://github.com/aerogear/aerogear-cordova-push\#ios.enable.bitcode
```

**Comment by faisakhtar** [comment]
Hi,

I am unable to run the commands above to perform the aerogear library update due to my development environment. 

Instead, I downloaded this updated aerogear lib file and manually copied it over the lib file in my Xcode project. Now the archive process completes successfully with bit code enabled, this new library appears to have resolved the bit code compilation issue when using aerogear cordova push for iOS.

Great job with this fix.

Thanks, Faisal.

**Comment by edewit** [comment]
@faisakhtar thanks for testing

**Comment by edewit** [comment]
related ios change: https://github.com/aerogear/aerogear-ios-push/pull/81#issuecomment-229648222

**Pull request merged**
