### PR TITLE
changed name for PushPlugin to AGPushPlugin

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [AGCORDOVA-83](https://issues.jboss.org/browse/AGCORDOVA-83)

### CODE REVIEW

**Comment by matzew** [comment]
:+1: 
any comments, @cvasilak ?

**Comment by cvasilak** [comment]
@edewit mind if you rebase

**Comment by cvasilak** [comment]
@edewit tested on helloword-cordova demo, successfully registered and received notifications :+1: to merge once rebase

**Comment by edewit** [comment]
rebased @cvasilak

**Comment by cvasilak** [comment]
landed https://github.com/aerogear/aerogear-cordova-push/commit/3c19ea1dc5435f5d2f5942233750fdc7df2fcc24

**Comment by matzew** [comment]
Needs to go to 1,0.x branch, according to the JIRA ticket

**Comment by edewit** [comment]
updated the jira ticket

**Pull request merged**
