### PR TITLE
add cold start detection for ios

### PR DESCRIPTION
**Pull request by powowbox**
How to test

Add the following code in the index.js
```javascript
 onNotification: function(event) {
        if ( event.coldstart )
            alert('coldstart');
}
```
Compile, deploy on an iOs device

1. Close the app, send a notification, click on the notification, alertbox is displayed
2. Put the app in background, send a notification, click on the notification, the alertbox is not displayed
3. Put the app in foreground, send a notification, the alertbox is not displayed.

### CODE REVIEW

**Comment by matzew** [comment]
@corinnekrych can you review ?

**Comment by edewit** [comment]
@matzew testing this right now

**Comment by edewit** [comment]
@powowbox works like a charm, don't know why we only had it for android great to see that it's now on iOS as well, thanks

**Comment by corinnekrych** [comment]
+1

**Comment by matzew** [comment]
@powowbox one question, I see you have forked the UPS from this repo:
https://github.com/C-B4/unifiedpush-server

Was there a specific reason to use that fork, instead of our upstream version ? 

Thanks!

**Pull request merged**
