### PR TITLE
AGCORDOVA-159 : Use readline module in androidBeforeInstall.js

### PR DESCRIPTION
**Pull request by chawax**
I used the readline module to read the lines a more reliable way.

### CODE REVIEW

**Comment by matzew** [comment]
@edewit @jcesarmobile mind doing a review ?

**Comment by jcesarmobile** [comment]
The code looks good, but will test it later on a W10 machine

**Comment by jcesarmobile** [comment]
Hi.
I've tested with your code, but I'm getting this error:

> 
> Error: cmd: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\Users\jcesar\Documents\proyectos\cordova\tests\AerogearTest2\platforms\android\aerogear-cordova-push\aerogear-dependencies.gradle' line: 15
> 
> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Plugin with id 'com.google.gms.google-services' not found.

**Comment by chawax** [comment]
That's strange ... This is the error I had before changing the script.
I had this message because the dependencies were not set correctly in build.gradle file. They were appended to the end of the file and not in the "dependencies" section.

**Comment by jcesarmobile** [comment]
You are right, with the current implementation it's appended to the end, but with your change it's not appended at all. There is no com.google.gms.google-services in the build.gradle when I use your version of the plugin

**Comment by jcesarmobile** [comment]
ok, found the problem, the file is being copied before being closed.

I've sent a PR to your repo with a fix

**Comment by jcesarmobile** [comment]
Hey, sent you another PR, it was failing to install in node 0.10.x

**Comment by jcesarmobile** [comment]
Now it works fine on mac and windows even with old node versions. Thanks for the PR!

**Pull request merged**
