### PR TITLE
Cordova Metrics support

### PR DESCRIPTION
**Pull request by edewit**
Windows android and iOS support, to test add `sendMetricInfo` in json:

```json
{
            "pushServerURL": "<host url e.g http://server:port/ag-puhs>",
            "sendMetricInfo": true,
```

For testing windows be sure to add the windows page parameter:

```json
{
     "message": {
      "alert": "Hello metrics",
      "windows": { 
          "page": "cordova" 
       }
     }
```

### CODE REVIEW

**Comment by edewit** [comment]
@sebastienblanc care to take a look?

**Comment by corinnekrych** [comment]
:eyes: too

**Comment by sebastienblanc** [comment]
:eyeglasses:

**Comment by corinnekrych** [comment]
@sebastienblanc As discussed with @edewit to avoid compilation issue for ios plugin, we need AGPushPlugin.h to be modify to add @property

**Comment by corinnekrych** [comment]
+1 on iOS
I've used HelloWorld app tpo test it, i only had to change the push-config.json to included:
```"sendMetricInfo": true,```
Tested for background and newly launched app. Both cases send metrics ok.

**Comment by sebastienblanc** [comment]
+1 on Android , I will test on Windows tomorrow morning

**Comment by corinnekrych** [comment]
PS: @edewit don't forget to put in your PR ```AGPushPlugin.h``` modified with chanelId property.

**Pull request merged**
