### PR TITLE
if alert is complex ios 8 then change it back to string

### PR DESCRIPTION
**Pull request by edewit**
fix for [AGCORDOVA-106](https://issues.jboss.org/browse/AGCORDOVA-106)

`alert-extra` key will have the original alert object in case someone needs these settings in the callback

### CODE REVIEW

**Comment by edewit** [comment]
@matzew like this?

**Comment by matzew** [comment]
@corinnekrych can you take a look instead of me ?

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
+1
I tested it with HelloWorld local server and UPS 1.0.3 openshift one.
All fine. let me merge....

**Pull request merged**
